spring:
  datasource:
    url: jdbc:h2:mem:base
    driverClassName: org.h2.Driver
    username: root
    password:
  config:
    import: optional:file:.env[.properties]

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate.format_sql: true

spring.h2.console:
  enabled: true
  path: /h2-console
  settings:
    web-allow-others: true

spring.elasticsearch:
  rest:
    uris: ${ELASTICSEARCH_URI}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    connection-timeout: 10s
    read-timeout: 60s

server:
  port: ${PORT}

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

